### ISSUE TITLE
Ventura required

### ISSUE THREAD

**Issue by rubyredrick** [dataFude-app/dataFude#10]
### Discussed in https://github.com/dataTile-app/dataTile/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **rubyredrick** December  2, 2022</sup>
I tried to install via TestFlight but it says MacOS 13 is required. although the web site says MacOS 12. I'm still waiting on a few crucial apps to be compatible before I can upgrade.</div>

**Comment by icanzilb** [comment]
I'm going to close this issue — the requirement has been lowered to macOS 12 before the official launch in January
